language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.11.0
  - 2.11.1
  - 2.11.2
  - 2.11.3
  - 2.11.4
  - 2.11.5
  - 2.11.6
  - 2.11.7

jdk:
  - oraclejdk7
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
